import {
  About,
  Blog,
  Cta,
  Hero,
  Property,
  Features,
  Service,
} from "@/components/home/HomeSections";

// Tu peux aussi override les metadata sur une page une particulier :
// export const metadata = {
//   title: "Yombal - Trouvez la maison de vos rêves.",
//   description: "Generated by create next app and used by 2 idiots in Senegal.",
// };

export default function HomePage({}) {
  return (
    <>
      <main>
        <article>
          <Hero />

          <About />

          <Service />

          <Property />

          <Features />

          <Blog />

          <Cta />
        </article>
      </main>
    </>
  );
}
